### ISSUE TITLE
Broken Mixin in versions prior to 1,21

### ISSUE THREAD

**Issue by Shnupbups** [Deftu/Favorita#10]
The mixin for drawing the hotbar overlay causes the game to crash on startup on versions prior to 1.21, as `RenderTickCounter` was only introduced in 1.21. In prior versions, it takes a float tickDelta.
On a code analysis, it seems you attempted to account for this, but accidentally typed `if MC >= 1.20.1` instead of `if MC >= 1.21` in the mixin, causing this issue.
https://github.com/Deftu/Favorita/blob/d19d370c4b564fb97a9c7d1932fc0ceef2e55f65/src/main/java/dev/deftu/favorita/mixins/client/Mixin_DrawHotbarOverlay.java#L67C13-L68C41

**Comment by Deftu** [comment]
Thanks for the report! Can't believe I had missed this. I rewrote the majority of this Mixin while half-asleep, so I'm not surprised that I made such a silly mistake. I'll have this fixed in the next release.
