### ISSUE TITLE
Favorita Version 0.3.0 Forge MC 1.12.2 Save not the Items then you play in Creative

### ISSUE THREAD

**Issue by Titoo8899** [Deftu/Favorita#6]
Hi,
I have testet the Mod and this mod work not. I can set the lock on my Inventory Places then I have a Item on this Place but then I on the Crash can will click to clear all other thinks the Lock items was clear and ignore lock function.

What have I make:
1. Download the mod and put in the Mod folder
2. Start a new MC World in Creative
3. Open the Tabs and Place items in your inventory Tab
4. Lock now the Items
5. Go to the Trace Can in the Creative Tab and make Shift + left click (This clear normal all Items then no Mod this blocks)
6. See now the Clear Inventory who all Items was clear
7. The Mod have no Items save and have in this time not Work

Please fix this Bug.

**Comment by Deftu** [comment]
Hey! This wasn't a feature advertised in the mod, though it's an oversight on my part not to include it. I will be working on this feature for 0.4.0.

**Comment by Titoo8899** [comment]
Ah okay and I was happy then I can help find a bug etc.
